### ISSUE TITLE
Error when using bliss + underscore + browserSync (liveReload)

### ISSUE THREAD

**Issue by slavikse** [LeaVerou/bliss#39] opened 2015-12-07 22:49 UTC
The error seen when using the browserSync - stops working liveReload, in its absence, there is no error.
Please fix as soon as possible :)

The text of the error:
Uncaught TypeError: Cannot read property 'listeners' of undefined
A block of code:
...
// Hijack addEventListener and removeEventListener to store callbacks
...			
var listeners = this[_].bliss.listeners = this[_].bliss.listeners || {};
...

ps: thanks for such a wonderful library! :)
pss: please add versioning for convenience

**Comment by LeaVerou** [comment] 2015-12-07 23:01
This very weird. Which line number is it reporting for the error (the code you pasted occurs in two places).
Any chance you could put a `console.log(this);` line there and tell me what it prints?

**Comment by slavikse** [comment] 2015-12-07 23:34
Error with package underscore, rechecked link libraries and the exclusion underscore, the error disappeared.
I conclude that combined bliss + underscore + browserSync (liveReload) appears the error.

ps: console.log (this) - I do not understand what you want me to write? :)
check yourself :) underscore + bliss + browserSync (function - liveReload)

**Comment by zdfs** [comment] 2015-12-07 23:46
@slavikse - Is there any more information you can give us? None of us are using your unique environment. Not sure how to duplicate or where the error is being thrown.

**Comment by zdfs** [comment] 2015-12-08 20:55
Closing this out. If you have more information that we can act on, feel free to reopen.

**Closed by zdfs** 2015-12-08 20:55 UTC
Labels: Need more info

**Comment by spheroid-** [comment] 2016-01-15 08:31
This bug can be reproduced in Chrome by using Underscore and Bliss together and attempting to call window.addEventListener() like in http://codepen.io/anon/pen/PZJPpG.

It looks like the Bliss property '_' clashes with window._ so as an workaround I've changed the property to '__' and everything is fine now.

For some reason this bug does not reproduce on Safari, just Chrome.

**Comment by fredrikekelund** [comment] 2016-11-22 15:37
I'm getting the same error in Firefox. All I need to do is include both bliss and lodash, and then call `addEventListener` on `window`. @spheroid- has it right, it's a name collision, could probably be helped by checking in bliss if `this[_] instanceof Bliss` or something similar.

**Comment by LeaVerou** [comment] 2016-12-07 17:50
FWIW, you can change the name of the `_` property, as described [in the docs](http://blissfuljs.com/docs.html#configuration)
