### ISSUE TITLE
Modify exports for use with commonjs/es6 modules

### ISSUE THREAD

**Issue by tracker1** [LeaVerou/bliss#107] opened 2015-12-14 17:52 UTC
It would be nice if you exported (test for module/module.exports as well as self) then exports against $, $$ so that they can be imported directly...

``` js
(function (context){
  context.$ = $;
  context.$$ = $.$;
}(
  typeof module !== 'undefined' && module.exports 
  || typeof self !== 'undefined' && self || this)
);
```

This way it can be used via cjs modules built via browserify/webpack or via es6 imports via babel as such.

```
import {$,$$} from 'blissfuljs';
```

Alternatively, if `module.exports` exists, `module.exports = Bliss` and assume "shy" mode.

**Comment by LeaVerou** [comment] 2015-12-14 18:36
Sure! PR?

**Comment by oriSomething** [comment] 2015-12-24 18:19
i think, that actually rollup might be a better tool for packaging it:
- because the compact syntax would be cleaner, more compact and much closer to the current source
- browserify / webpack tends to leave fingerprints because the way it work

**Comment by renoirb** [comment] 2016-01-02 16:55
It depends how and where Bliss will run. Only in a browser with an anonymous `<script src="bliss.js"></script>` or elsewhere like we do in Backbone/Require.js, or as a `document` "free" DOM manipulator (i.e. outside of the global `document` scope we get in a browser), or even in Node.js.

My concern is not how we load it, because we can always use `require.config({shim:{}});` or similar, but more on how we can test an instance of bliss. Testing `bliss.shy = true;` doesn’t seem doable with current test infrastructure in the way it's written. (Notice: I am not a testing expert, and couldn’t make it work yet.)

**Comment by cyrilchapon** [comment] 2017-12-28 09:30
Is there a way to use it in an ES6, babel, webpack env right now ? :)

**Comment by joyously** [comment] 2018-06-12 15:36
Does this article help?
https://philipwalton.com/articles/deploying-es2015-code-in-production-today/

**Comment by LeaVerou** [comment] 2018-06-12 17:20
@tracker1 Agreed! Pull request?

**Comment by matthiask** [comment] 2018-11-06 08:17
I don't know how to solve this "correctly", but [here's what I'm doing](https://406.ch/writing/using-bliss-with-webpack/):

First, `yarn add https://github.com/LeaVerou/bliss/` (you can also use a released versions, but why not use the latest and best version of Bliss?)

Then, once:

```
import 'blissfuljs/bliss.shy.js'
import 'blissfuljs/bliss._.js'
```

Afterwards, in all files where you want to use Bliss, do this:

```
const {$, $$} = window  // eslint-disable-line
```

The `eslint-disable-line` comment stops [ESLint](https://eslint.org/) from complaining about unused variables. In this case I'm fine with not having to add and remove `$` and `$$` on a case-by-case basis.

**Comment by LeaVerou** [comment] 2020-10-21 17:49
FWIW, I'm currently doing a rewrite of Bliss to use ESM. Should I close this as a duplicate of #226, since once that's complete, this will be resolved too?

**Comment by matthiask** [comment] 2020-10-21 18:24
@LeaVerou Closing as a duplicate makes sense to me.

**Closed** 2020-10-22 14:36 UTC
Labels: enhancement

**Comment by tracker1** [comment] 2020-11-15 01:47
I'm really sorry for not responding sooner, usually try to check GH notices a few times a week, but the past couple months have been abnormally busy... @LeaVerou cool beans on the rewrite.  Honestly should have done a PR much sooner.
