### ISSUE TITLE
Github banner overlays header on the docs index

### ISSUE THREAD

**Issue by kurtextrem** [LeaVerou/bliss#92] opened 2015-12-12 09:15 UTC
http://prntscr.com/9d7xbp
Is this only me? (http://blissfuljs.com/docs.html) (Chrome v49, Dev channel)
Upon clicking some heading (e.g. Overview or Vanilla) it disappears.

**Comment by guoguo12** [comment] 2015-12-12 13:59
Nope, same for me. Similarly, scrolling to the very bottom of the page causes the table of contents to overlap with the footer.

**Comment by zdfs** [comment] 2015-12-15 04:38
Seems like this one can be closed for #119.

**Comment by guoguo12** [comment] 2015-12-15 04:47
I'm pretty sure those are different.

**Comment by zdfs** [comment] 2015-12-15 05:03
The behavior captured in this bug doesn't seem to apply anymore, unless you can reproduce somehow? I may be missing something.

**Comment by guoguo12** [comment] 2015-12-15 05:07
I still see this on the live page (http://blissfuljs.com/docs.html) on Chrome/FF. (This only shows up if your browser window is wide/tall enough.)

**Comment by dperrymorrow** [comment] 2015-12-15 05:08
Yup, has to be a tall win, 900px or taller

![bliss js documentation 2015-12-14 21-07-40](https://cloud.githubusercontent.com/assets/64978/11802547/c442f118-a2a6-11e5-90d8-4512607fdb6e.png)

**Comment by zdfs** [comment] 2015-12-15 05:09
That must be my problem. I don't have that luxury at the moment.

**Comment by dperrymorrow** [comment] 2015-12-15 05:10
you could zoom out to the browser window to repro

**Comment by guoguo12** [comment] 2015-12-15 05:12
Ah, okay. You could also use Chrome's mobile view emulator.

At a technical level, this issue is pretty simple: there are two overlapping elements. The problem is that there's no obvious better place to put the ribbon. Anyone have any ideas?

**Comment by zdfs** [comment] 2015-12-15 05:17
When the window is that large, we could put the ribbon on the bottom right corner of the viewport?

**Comment by guoguo12** [comment] 2015-12-15 05:20
I don't know, that seems like an unnatural place to put a ribbon.

I see two possibilities:

1. Move the table of contents down so that it's below the ribbon.
2. Get rid of the ribbon entirely. It's a distraction, and there's already the GitHub star counter in the top-right corner.

**Comment by dperrymorrow** [comment] 2015-12-15 06:03
or you could make it fixed top right.
and move the github button over with some margin.

**Comment by guoguo12** [comment] 2015-12-15 06:04
Ooh, I like that idea.

**Comment by dperrymorrow** [comment] 2015-12-15 06:16
ill give that a go if nobody has fixed it by morning if everyone is on board with that.

**Comment by guoguo12** [comment] 2015-12-15 18:07
@dperrymorrow: Do you still want this one? If not, I could do it.

**Comment by dperrymorrow** [comment] 2015-12-15 18:30
go for it, I'm pretty busy today actually

**Comment by LeaVerou** [comment] 2015-12-15 18:47
Part of the problem here is that these should never touch, the media query is wrong. See #119

**Comment by guoguo12** [comment] 2015-12-15 18:57
Oh, so should the "Contents" heading be under the ribbon?

**Comment by LeaVerou** [comment] 2015-12-15 20:42
Yup. They should never overlap. Them overlapping is a bug in the media queries. It should have become 2 columns with that height and if that doesn't fit either, then position:static and in line with the rest of the content (which is what happens in smaller screens). Therefore, closing this as a duplicate of #119.

**Closed by LeaVerou** 2015-12-15 20:42 UTC
Labels: bug
